// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "prisma/config";

import { loadDevEnvFiles } from "./scripts/lib/env-files.mjs";

// Resolves DATABASE_URL (and anything else) with the same `.env*`
// precedence `next dev` uses, not just `.env` -- a bare `import
// "dotenv/config"` (Prisma's generated default, replaced here) only ever
// read `.env` in the current working directory, so a DATABASE_URL set only
// in `.env.local` was invisible to every `prisma` command, including the
// `prisma migrate deploy` scripts/check-migrations.mjs runs ahead of
// `next dev`. See scripts/lib/env-files.mjs for the exact order and why
// (ugcportal-h2yd).
loadDevEnvFiles({ cwd: path.dirname(fileURLToPath(import.meta.url)) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Falls back to a local SQLite file so `prisma migrate`/`generate` work
    // out of the box without requiring a .env file for local development.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
