-- ugcportal-15r: the uploader's own rights attestation, per file.
--
-- docs/legal/manual-upload-rights-review.md §3.1. Until now every per-upload
-- rights fact the sellability gate reads was an ADMIN's assertion about a file
-- the admin did not make (`MediaListing`'s triage booleans), and the uploader
-- — the only person who can know whether they took the photograph — was never
-- asked anything. This table is where the asking is recorded.
--
-- Generated by `prisma migrate diff --from-migrations prisma/migrations
-- --to-schema prisma/schema.prisma --script`; the comments are the only
-- hand-edit.
--
-- ONE NEW TABLE, NOTHING ALTERED AND NOTHING BACKFILLED. No column is added to
-- Media or MediaListing and no existing row is touched. An upload that existed
-- before this ran has no attestation, and the gate reads that absence as
-- `attestation_missing` (src/lib/resale-rights.ts) — which is the honest
-- state, not a regression: nobody ever asked those uploaders anything, so
-- there is no answer for a backfill to recover and inventing one would be the
-- system warranting rights on a person's behalf.
--
-- EVERY ANSWER COLUMN IS `NOT NULL` AND NONE OF THEM HAS A DEFAULT, which is
-- the exact opposite of the choice 20261006120000 made for
-- `MediaListing.depictsMinors` — and both are the fail-closed choice for their
-- own table. A triage column is added to rows that already exist, so it has to
-- be nullable and NULL has to mean "not answered yet". An attestation ROW only
-- ever comes into existence as a complete set of answers written in one
-- statement by the single write path (POST /api/media), so there is no moment
-- at which a half-filled one is legitimate. A `DEFAULT 0` here would be the
-- database answering "no" to "does this show a child" on the uploader's behalf,
-- below the validator, where nothing would notice. `NOT NULL` with no default
-- makes that row unwritable instead: ugcportal-15r K4 — "not asked" and
-- "answered no" must stay distinguishable — is enforced by the shape of the
-- table, with "not asked" being no row at all. Asserted against the real DDL
-- in src/lib/attestation-migration.test.ts rather than trusted to this comment.
--
-- `mediaId` IS UNIQUE: one declaration per file. Two would leave the gate
-- choosing between two answers to the same question, the same reason
-- `MediaRightsClearance` is unique on (listingId, layer).
--
-- BOTH FOREIGN KEYS ARE `ON DELETE CASCADE`, unlike the `RESTRICT` the
-- BenefitSource pointers carry. An attestation is one person's statement about
-- their own file: there is nothing left to say once either the file or the
-- person is gone, and a RESTRICT on `attestedByUserId` would make a GDPR
-- erasure fail rather than complete. docs/access-control.md's delete-cascade
-- runbook gains a row for it (checked by src/lib/access-control-doc.test.ts,
-- which parses the schema rather than trusting the doc).
--
-- DEPLOY ORDER IS UNCONSTRAINED in the usual direction — this only CREATEs, so
-- a build that has never heard of the table keeps working. The reverse is NOT
-- free here, and this is the one migration in this series where it is worth
-- saying so: a build that HAS heard of it, running against a database where
-- this has not been applied, fails on every upload AND on every read that uses
-- MEDIA_GATE_SELECT, because that select now names the relation. Apply before
-- the swap.

-- CreateTable
CREATE TABLE "MediaAttestation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "mediaId" TEXT NOT NULL,
    "attestedByUserId" TEXT NOT NULL,
    "attestationVersion" TEXT NOT NULL,
    "attestedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "authorship" TEXT NOT NULL,
    "ownOriginalNotFromWeb" BOOLEAN NOT NULL,
    "showsIdentifiablePeople" BOOLEAN NOT NULL,
    "showsMinors" BOOLEAN NOT NULL,
    "containsMusicNotOwned" BOOLEAN NOT NULL,
    "otherCreativeContributor" BOOLEAN NOT NULL,
    "brandOrSponsorship" BOOLEAN NOT NULL,
    "aiGenerated" BOOLEAN NOT NULL,
    "uploaderIsAdult" BOOLEAN NOT NULL,
    CONSTRAINT "MediaAttestation_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "Media" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MediaAttestation_attestedByUserId_fkey" FOREIGN KEY ("attestedByUserId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
--
-- One declaration per file; see the note above.
CREATE UNIQUE INDEX "MediaAttestation_mediaId_key" ON "MediaAttestation"("mediaId");

-- CreateIndex
--
-- SQLite does not index a child foreign key automatically, and the CASCADE
-- above is what needs one: deleting a user means finding every attestation
-- that names them, which without this index is a full scan of this table.
CREATE INDEX "MediaAttestation_attestedByUserId_idx" ON "MediaAttestation"("attestedByUserId");
