-- ugcportal-ei7: make the public feed's index partial, so its size tracks
-- published, preview-bearing rows rather than the whole Media table. Same
-- index name as before (Media_createdAt_id_idx), so this is a straight
-- DROP+CREATE of the one index, not a second index duplicating its job.
--
-- The WHERE clause is deliberately identical to the predicate GET
-- /api/public/media already applies (PUBLIC_MEDIA_SCOPE in
-- src/lib/public-media.ts): publishedAt, previewKey and previewId all
-- IS NOT NULL. Generated by `prisma migrate diff --from-migrations
-- prisma/migrations --to-schema prisma/schema.prisma --script` against the
-- schema's `@@index([createdAt, id], where: raw(...))` — see the comment on
-- that index in prisma/schema.prisma for the full rationale and the
-- before/after EXPLAIN QUERY PLAN measurement.
--
-- DEPLOY COST: both statements below take SQLite's write lock on Media for
-- their duration, and DROP INDEX followed by CREATE INDEX is a full table
-- scan to rebuild the index, not an O(1) metadata change — on a Media table
-- much larger than this repo's today, that is a write-lock window sized to
-- the whole table, during which every write to Media (an upload, a publish,
-- a preview write) blocks. Run this migration in a quiet window once Media
-- is large enough for that scan to be noticeable.

-- DropIndex
DROP INDEX "Media_createdAt_id_idx";

-- CreateIndex
CREATE INDEX "Media_createdAt_id_idx" ON "Media"("createdAt", "id") WHERE publishedAt IS NOT NULL AND previewKey IS NOT NULL AND previewId IS NOT NULL;
