-- ugcportal-qnq9.3: the other half of §3.1a's two-fact model, plus the
-- brand-eligibility answer K4 refuses a benefit on.
--
-- Generated by `prisma migrate diff --from-migrations prisma/migrations
-- --to-schema prisma/schema.prisma --script`; the comments are the only
-- hand-edit.
--
-- MediaListing.wineAccessory — IS THE SUBJECT AN ACCESSORY. 20261006160000
-- added `depictsAlcohol`, which is the half that refuses. This is the half
-- that permits, and §3.1a is explicit that it must: the site's chosen angle
-- is wine accessories — empty glasses, coolers, tool-type apps — and those
-- are monetisable precisely because they are not the drink. The two answers
-- are independent, so this is a column of its own rather than a shade of the
-- other one: a cooler with labelled bottles on its shelf is an accessory AND
-- shows alcohol, and only `depictsAlcohol` decides that case.
--
-- NULLABLE, WITH NO DEFAULT, like every triage column before it — but for a
-- narrower reason, and the difference is worth stating because it is the
-- difference between this fact and the other six. A `DEFAULT 0` here would
-- not assert anything dangerous; it would assert "not an accessory", which
-- is the answer that permits nothing extra. What it would destroy is the
-- distinction between an item nobody has classified and one classified as
-- ordinary content, and the gate refuses the first of those
-- (`triage_incomplete`) while selling the second. That distinction is the
-- whole mechanism (ugcportal-qn3), and a default is how a migration quietly
-- answers a question on a human's behalf.
--
-- RightsLayer gains WINE_ACCESSORY in the same change and needs no DDL:
-- Prisma maps enums to TEXT on SQLite. A MediaRightsClearance row naming it
-- is inert — the fact is registered `settledBy: "recorded"`, which has no
-- blocker for a clearance to lift.
--
-- BenefitSource.alcoholLinked / alcoholAnsweredAt / alcoholAnsweredByUserId —
-- WHO IS BEHIND THE BRAND. §3.1a practical rule 1: "Before any paid deal,
-- check who's behind the brand. If the company also produces, imports or
-- sells alcohol, decline." That is a fact about a company, so it lives on the
-- company's row, answered once and dated, rather than being re-asked per
-- photograph.
--
-- `alcoholLinked` IS NULLABLE WITH NO DEFAULT, AND NULL REFUSES. This is the
-- strongest form of the no-default argument in this file: here a
-- `DEFAULT 0` would read as "no brand anyone has ever named sells alcohol",
-- which is the fail-open direction on the one question §3.1a says to ask
-- before taking money. Every BenefitSource row that already exists gets NULL
-- and is therefore unchecked, and `alcoholLinkedBrandRefusal`
-- (src/lib/alcohol-commerce.ts) refuses an unchecked brand exactly as it
-- refuses an alcohol-linked one. There is no backfill: the answer requires
-- looking up a company, which no SQL here is doing.
--
-- The BenefitSource table is REDEFINED rather than ALTERed because SQLite
-- cannot add a column with a foreign-key constraint in place; the
-- INSERT ... SELECT below carries every pre-existing row across with its
-- three new columns left NULL, which is the state the paragraph above
-- describes.

-- AlterTable
ALTER TABLE "MediaListing" ADD COLUMN "wineAccessory" BOOLEAN;

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_BenefitSource" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "alcoholLinked" BOOLEAN,
    "alcoholAnsweredAt" DATETIME,
    "alcoholAnsweredByUserId" TEXT,
    CONSTRAINT "BenefitSource_alcoholAnsweredByUserId_fkey" FOREIGN KEY ("alcoholAnsweredByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_BenefitSource" ("createdAt", "id", "name", "slug", "updatedAt") SELECT "createdAt", "id", "name", "slug", "updatedAt" FROM "BenefitSource";
DROP TABLE "BenefitSource";
ALTER TABLE "new_BenefitSource" RENAME TO "BenefitSource";
CREATE UNIQUE INDEX "BenefitSource_slug_key" ON "BenefitSource"("slug");
CREATE INDEX "BenefitSource_alcoholAnsweredByUserId_idx" ON "BenefitSource"("alcoholAnsweredByUserId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

