-- Subject tags on media (ugcportal-jsc).
--
-- Schema half generated by `prisma migrate diff --from-migrations
-- --to-schema --script`, so it is exactly what the datamodel describes and
-- `migrate diff` reports no drift afterwards. The seed at the bottom is the
-- hand-written part.

-- CreateTable
CREATE TABLE "Tag" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "_MediaToTag" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_MediaToTag_A_fkey" FOREIGN KEY ("A") REFERENCES "Media" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_MediaToTag_B_fkey" FOREIGN KEY ("B") REFERENCES "Tag" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Tag_slug_key" ON "Tag"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "_MediaToTag_AB_unique" ON "_MediaToTag"("A", "B");

-- CreateIndex
CREATE INDEX "_MediaToTag_B_index" ON "_MediaToTag"("B");

-- Seed the four subject areas in use (food, wine & drink, technology, books).
--
-- Data in a migration, which deserves a justification rather than a shrug.
-- These four are the vocabulary the product ships with; without them the
-- upload page's tag picker is empty on day one and the first uploader has to
-- invent the site's taxonomy. They are rows and not an enum precisely so a
-- fifth is an INSERT rather than a migration — seeding the first four does not
-- change that, and nothing in the application treats these ids or slugs as
-- special.
--
-- `INSERT OR IGNORE`, keyed on the unique `slug`, so applying this against a
-- database where somebody already created "food" leaves their row (and its
-- existing associations) alone instead of failing the migration.
--
-- The ids are fixed strings rather than cuids because a migration has no
-- generator to call; nothing derives meaning from their shape, and `Tag.id` is
-- never serialised to any audience (see MEDIA_TAGS_SELECT in
-- src/lib/media-access.ts, which projects slug and name only).
INSERT OR IGNORE INTO "Tag" ("id", "slug", "name") VALUES
    ('tagseed000food', 'food', 'Food'),
    ('tagseed000wine', 'wine-drink', 'Wine & drink'),
    ('tagseed000tech', 'technology', 'Technology'),
    ('tagseed000book', 'books', 'Books');
