-- ugcportal-qnq9.2.1: the commercial outbound link as a record of its own —
-- destination, network and the brand at the other end.
--
-- Forbrukertilsynet requires a page carrying affiliate links to be labelled at
-- the top AND at each link (docs/ugc-research.md §3.2, §2 step 5, §5.7).
-- 20261006150000 added the top-of-page half (MediaAdvertisingDisclosure.label).
-- This adds the thing the per-link half will be rendered from
-- (ugcportal-qnq9.2.2); nothing renders it yet.
--
-- Generated by `prisma migrate diff --from-migrations prisma/migrations
-- --to-schema prisma/schema.prisma --script`; the comments are the only
-- hand-edit.
--
-- ONE NEW TABLE, NOTHING ALTERED AND NOTHING BACKFILLED. No column is added to
-- Media, MediaListing or BenefitSource, and no existing row is touched. An item
-- that existed before this ran has no commercial links, which is both the
-- honest state and the one that publishes exactly as it did before — there is
-- no affiliate link anywhere in this product's history for a backfill to
-- recover.
--
-- DEPLOY ORDER IS UNCONSTRAINED, for the reason 20261006150000 gives at
-- length: this only CREATEs, so a build that has never heard of the table keeps
-- working, and a new build against an un-migrated database fails only on the
-- commercial-link route rather than on every page. Applying it before the swap
-- is still the right order; it is just not load-bearing here.
--
-- `networkOther` IS THE ONLY NULLABLE COLUMN AND IT HAS NO DEFAULT. It names
-- the network when `network = 'OTHER'` and is NULL for the five members the
-- research document names. A `DEFAULT ''` would make "no name was given" and
-- "the name is the empty string" the same row, which is exactly the state the
-- write path refuses — and it would do it in SQL, below the validator, where
-- nothing would ever notice.
--
-- `benefitSourceId` IS NOT NULL, unlike MediaAdvertisingDisclosure's own
-- nullable copy of the same pointer. A disclosure has states with no brand
-- ("no benefit received", "not answered"); a commercial link does not. §3.1a
-- practical rule 1 ("check who's behind the brand") is a question about a
-- company, and a link with no company recorded is a link nobody can ever ask it
-- of. The NOT NULL is what makes `alcoholLinkedBrandRefusal`
-- (src/lib/alcohol-commerce.ts) total over every row in this table rather than
-- over most of them.
--
-- `mediaId` IS ON DELETE CASCADE and `benefitSourceId` ON DELETE RESTRICT, the
-- same split MediaAdvertisingDisclosure makes: the link is a statement about
-- the item and there is nothing left to point at once the item is gone, while a
-- brand is shared vocabulary whose deletion must not quietly erase where a
-- published link pointed. docs/access-control.md's delete-cascade runbook
-- gains a row for the first of those (checked by
-- src/lib/access-control-doc.test.ts, which parses the schema rather than
-- trusting the doc).

-- CreateTable
CREATE TABLE "CommercialLink" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "mediaId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "network" TEXT NOT NULL,
    "networkOther" TEXT,
    "benefitSourceId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "CommercialLink_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "Media" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CommercialLink_benefitSourceId_fkey" FOREIGN KEY ("benefitSourceId") REFERENCES "BenefitSource" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
--
-- SQLite does not index a child foreign key automatically, and the RESTRICT
-- above is what needs one: enforcing it means answering "does any commercial
-- link still point at this brand" on every attempted BenefitSource delete,
-- which without this index is a full scan of this table. The same argument
-- 20261006150000 makes for MediaAdvertisingDisclosure_benefitSourceId_idx.
CREATE INDEX "CommercialLink_benefitSourceId_idx" ON "CommercialLink"("benefitSourceId");

-- CreateIndex
--
-- One destination at most once per item. A double-submitted form is the
-- ordinary way a duplicate arrives, and two identical labelled links under one
-- photograph are a rendering defect nobody chose; the route answers 409 rather
-- than reporting a success that did not happen.
--
-- It is also the index the renderer's read goes through — SQLite will use a
-- composite index for its leading column — which is why there is no second
-- index on `mediaId` alone.
CREATE UNIQUE INDEX "CommercialLink_mediaId_url_key" ON "CommercialLink"("mediaId", "url");
